### ISSUE TITLE
SciTEDebug.ahk error vSP_Console

### ISSUE THREAD

**Issue by tdalon** [fincs/SciTE4AutoHotkey#32] opened 2020-10-21 06:53 UTC
See here https://www.autohotkey.com/boards/viewtopic.php?t=6635
When starting debugging I get following error:
![SciTE4AutoHotkey  1 of 3   Debugging](https://user-images.githubusercontent.com/6458444/96683718-d0813a80-137a-11eb-8a89-f210e6ee0dcd.png)

**Comment by joedf** [comment] 2020-10-23 14:45
Do you have steps to reproduce this reliably?

**Comment by fincs** [comment] 2022-05-28 12:56
Closing this issue due to Lexikos's debugger changes being integrated.

**Closed by fincs** 2022-05-28 12:56 UTC
